name: Send Email

on:
  push:

jobs:
  send-mail:
    runs-on: ubuntu-latest

    steps:
      - name: Send mailer
        uses: dawidd6/action-send-mail@v3
        with:
          host: smtp.gmail.com
          port: 587
          account: ${{ secrets.SMTP_USER }}
          password: ${{ secrets.SMTP_PASS }}

          sender: Pietje Puk <pietjepuk0968@gmail.com>
          from: pietjepuk0968@gmail.com

          to: 2403737duvan@zuyd.nl

          subject: Test mail van GitHub Actions
          body: Gekke shit
