# Bestand: .github/workflows/send-mail.yml
name: Send Email

on:
  push:
    branches:
      - master

jobs:
  send-mail:
    runs-on: ubuntu-latest

    steps:
      - name: Send mailer
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: smtp.gmail.com
          server_port: 587

          username: ${{ secrets.SMTP_USER }}
          password: ${{ secrets.SMTP_PASS }}

          subject: "Nieuwe commit in de repo: ${{ github.sha }}"
          body: |
            Ewa drerrie ,

            Er is wat gepusht door ${{ github.actor }}.

            Commit message:
            ${{ github.event.head_commit.message }}

            Commit SHA: ${{ github.sha }}
            
          to: 2403737duvan@zuyd.nl
          from: pietjepuk0968@gmail.com
